# Generated by Django 5.0.7 on 2026-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0009_feedback_clientfeedback_providerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='problem_photo',
            field=models.ImageField(blank=True, null=True, upload_to='problem_photos/'),
        ),
    ]
