# Generated by Django 5.0.7 on 2026-03-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0011_booking_description_alter_booking_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
